services:
  backend:
    build:
      context: ./backend
    image: solo-adventure-picker-backend
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/app
    environment:
      - DB_PATH=/app/solo-adventure-picker.db

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    volumes:
      - type: bind
        source: ./frontend
        target: /app
      - type: volume
        target: /app/node_modules
    environment:
      - vite_api_url=http://localhost:8080
    depends_on:
      - backend
